from string import ascii_letters, digits

ORIGINAL_LINK_LENGTH = 2048
SHORT_LENGTH = 16
REGEX_SHORT_VALIDATION = r'^[a-zA-Z0-9]{1,16}$'
VALID_SIMBOLS_RANGE = ascii_letters + digits
ATTEMPS_TO_COLLISION_COUNT = 2048
SHORT_GENERATION_LENGTH = 6
